site_name: Estrutura De Proejto ETL
theme:
  name: windmill-dark # or other theme
  palette:
    primary: blue
  language: en

repo_name: "Mathwesm/Estrutura_projeto"
repo_url: "https://github.com/Mathwesm/Estrutura_projeto"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
